name: Create Sound File for Music Score
description: Template for creating a new sound effect file for the game.
title: "Create Sound File for Score for..."
labels: [music, audio]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a description of the Music to be created.
      placeholder: "Enter the Music description..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide the context where this music will be used.
      placeholder: "Enter the context for the music..."
    validations:
      required: true

  - type: input
    id: file_path
    attributes:
      label: Save File Path
      description: Provide the full filepath where the file should be saved.
      placeholder: "Enter the full file path..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria:

        - [ ] The peak level is normalized to -1 dBFS.
        - [ ] The file is saved in `.ogg` file format.
        - [ ] The file has a sample rate of 44,100 Hz.
        - [ ] The file is located at the specified filepath: `{{file_path}}`-loop.
        - [ ] The filename ends in `-loop`
        - [ ] The file has been imported in godot (Godot opened) and has the accompanying `.import` file.
        - [ ] A pull request (PR) is created with the changes.

  - type: textarea
    validations:
      required: true
    attributes:
      id: subtasks
      label: Subtasks
      value: |
        - [ ] The peak level is normalized to -1 dBFS.
        - [ ] The file is saved in `.ogg` file format.
        - [ ] The file has a sample rate of 44,100 Hz.
        - [ ] The file is located at the specified filepath: `{{file_path}}`-loop.
        - [ ] The filename ends in `-loop`
        - [ ] The file has been imported in godot (Godot opened) and has the accompanying `.import` file.
        - [ ] A pull request (PR) is created with the changes.
        
        ## Blocking
        - Music Implementation tasks (Making the music play in-game)
        - Music leveling / mixing tasks (Making the crossfaade/blend and layer)
