name: Implementation
description: Template for Acceptance criteria for deliverables.
title: "Implementation Acceptance Criteria"
labels:
  - implementation
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a description of what your implementing.
      placeholder: "Enter the implementation description..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide the context for implementation.
      placeholder: "Enter the context for implementation..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria Guidelines:
        - [ ] Delete any filetype not needed for implementation in Subtasks.
        - [ ] Verify that the file is in the correct spot.

        ## File Path Standards
        - {folder_name}: Enter your own folder name if no other folder matches.
        - {model_name}: Enter the name of the model.
        - {file_name}: Enter the name of the file.
        - {Same Directory}: Same directory.
        - [Under Construction]: Developing SOP.

  - type: textarea
    validations:
      required: true
    attributes:
      id: subtasks
      label: Subtasks
      value: |
        ## Acceptance Criteria:
        
        ### Game Object (game_)
        - [ ] Add game_ as a prefix to the {file_name}
        - [ ] Import File Location: game/{folder_name}/game_{model_name}.tscn
        - [ ] Connect the asset to the scene: [Under Construction]
        
        ### Level (lvl_)
        - [ ] Add lvl_ as a prefix to the {file_name}
        - [ ] Import File Location: game/levels/{folder_name}/lvl_{file_name}.tscn
        - [ ] Connect the asset to the scene: [Under Construction]
        
        ### Material (mat_)
        - [ ] Add mat_ as a prefix to the {file_name}
        - [ ] Import File Location: common/art/materials/mat_{file_name}.material
        - [ ] Connect the asset to the scene: [Under Construction]
        
        ### Skeletal Mesh (sk_)
        - [ ] Add sk_ as a prefix to the {file_name}
        - [ ] Add animations (if needed)
        - [ ] Add textures (if needed)
        - [ ] GitHub Pull Request Created > Assign Reviewer.
        - [ ] Import File Location: game/{folder_name}/sk_{file_name}.blend
        - [ ] Import File Location: game/{folder_name}/sk_{file_name}.gltf
        #### Configure Import Settings
        - [ ] Physics Turned On > Physics > Shape Type > Simple Convex (Normally will work) 
        - [ ] Locate and right click on the .gltf file > New Inherited Scene
        - [ ] Save As > {Same Directory} > sk_{file_name}.tscn
        
        ### Sound (aud_)
        - [ ] Add aud_ as a prefix to the {file_name}
        - [ ] .ogg for music & ambient files, .wav for SFX files.
        - [ ] Import File Location: common/audio/{folder_name}/aud_{file_name}.ogg
        - [ ] Import as loop: add -loop to the end of the {file_name}: common/audio/{folder_name}/aud_{file_name}-loop.ogg
        - [ ] Connect the asset to the scene: [Under Construction]        
        
        ### Static Mesh (sm_)
        - [ ] Add sm_ as a prefix to the {file_name}
        - [ ] Add animations (if needed)
        - [ ] Add textures (if needed)
        - [ ] GitHub Pull Request Created > Assign Reviewer.
        - [ ] Import File Location: game/{folder_name}/sm_{file_name}.blend
        - [ ] Import File Location: game/{folder_name}/sm_{file_name}.gltf
        #### Configure Import Settings
        - [ ] Physics Turned On > Physics > Shape Type > Simple Convex (Normally will work) 
        - [ ] Locate and right click on the .gltf file > New Inherited Scene
        - [ ] Save As > {Same Directory} > sm_{file_name}.tscn

        ### Texture (tex_)
        - [ ] Add tex_ as a prefix to the {file_name}
        - [ ] GitHub Pull Request Created > Assign Reviewer.
        - [ ] Import File Location: game/{model_name}/tex_{model_name}.blend
        - [ ] Connect the asset to the scene: [Under Construction]  
